version: 0.2
phases:
  install:
    runtime-versions:
      python: 3.11  # Specify your python version here
    commands:
      - echo installing dependencies...
      - pip install -r requirements.txt
  pre_build:
    commands:
      - echo running tests...
  build:
    commands:
      - echo build started on `date`
      - echo building the Flask app...
artifacts:
  files:
    - '**/*'
  discard-paths: yes
